trigger:
- master
- develop
- release/*

pr:
- master
- develop

stages:
- stage: Build
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: Build
    steps:
    - task: PowerShell@2
      displayName: Build artifacts
      inputs:
        filePath: './build.ps1'
        arguments: '-Target Package'
        pwsh: true
    - task: CopyFiles@2
      displayName: Copy artifacts
      inputs:
        sourceFolder: '.dist'
        contents: '**'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: Package
- stage: Publish
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), eq(variables['Build.Reason'], 'Manual')))
  pool:
    vmImage: 'windows-latest'
  jobs:
  - deployment: Publish
    environment: NuGet-Public
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetToolInstaller@1
            displayName: 'Use NuGet 5.4.0'
            inputs:
              versionSpec: 5.4.0
          - task: NuGetCommand@2
            displayName: 'NuGet push packages'
            inputs:
              command: push
              packagesToPush: '$(Agent.BuildDirectory)/Package/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'NuGet - Meeg'
