//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeg.Kentico.ContentComponents.Cms.CMSFormControls {
    
    
    public partial class ContentComponent {
        
        /// <summary>
        /// ContentComponentForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.FormEngine.Web.UI.BasicForm ContentComponentForm;
    }
}
